name = "book-api"
compatibility_date = "2025-06-13"
main = "./dist/src/index.js"
# node_compat = true  

[build]
command = "bun run build"

[vars]
# Add environment variables here
ENVIRONMENT = "production"
NODE_ENV = "production"
CORS_ORIGIN = ""
